spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jobforme?sslmode=disable}
    username: ${SPRING_DATASOURCE_USERNAME:jobforme}
    password: ${SPRING_DATASOURCE_PASSWORD:jobforme}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE:10}
      data-source-properties:
        sslmode: ${SPRING_DATASOURCE_SSLMODE:disable}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
      encoding: UTF-8
      schema-locations: classpath:database/jobportal_schema_and_seed.sql
      continue-on-error: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jackson:
    serialization:
      write-dates-as-timestamps: false

  security:
    debug: true


jwt:
  secret: w7Qw6vQw6vQw6vQw6vQw6vQw6vQw6vQw6vQw6vQw6vQw6vQw6vQw6vQw==
  expiration-in-seconds: ${JWT_EXPIRATION:3600}

file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads/cv}

logging:
  level:
    org.springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
